spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_test
    username: postgres
    password: 1596psql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

server:
  port: 8081
